In [6]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print("The concatenated array is: ")
print(arr)

The concatenated array is: 
[1 2 3 4 5 6]


In [7]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
arr=np.concatenate((arr1,arr2),axis=1)
print("The concatenated array is: ")
print(arr)

The concatenated array is: 
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [8]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
arr=np.concatenate((arr1,arr2),axis=0)
print("The concatenated array is: ")
print(arr)

The concatenated array is: 
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]


In [9]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
arr=np.stack((arr1,arr2),axis=1)
print("The stacked array is: ")
print(arr)

The stacked array is: 
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [11]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
arr=np.stack((arr1,arr2),axis=0)
print("The stacked array is: ")
print(arr)

The stacked array is: 
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [14]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
arr=np.hstack((arr1,arr2))
print("The stacked array along rows is: ")
print(arr)

The stacked array along rows is: 
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [15]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
arr=np.vstack((arr1,arr2))
print("The stacked array along rows is: ")
print(arr)

The stacked array along rows is: 
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]


In [16]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
arr=np.dstack((arr1,arr2))
print("The stacked array along rows is: ")
print(arr)

The stacked array along rows is: 
[[[1 4]
  [2 5]
  [3 6]]

 [[4 7]
  [5 8]
  [6 9]]]
