In [1]:
import numpy as np
list1=[1,2,3,4,5]
arr=list1[1:3]
print(arr)

[2, 3]


In [3]:
arr=np.array([[1,2,3,4,5],[3,4,5,6,7],[9,8,7,6,5]])
print("The Numpy Array is: ")
print(arr)
arr1=arr[1:3,:3]
print("The sliced numpy is: ")
print(arr1)

The Numpy Array is: 
[[1 2 3 4 5]
 [3 4 5 6 7]
 [9 8 7 6 5]]
The sliced numpy is: 
[[3 4 5]
 [9 8 7]]


In [4]:
arr=np.array([1,2,3,4,5])
print(arr[1:3])

[2 3]


In [5]:
arr=np.array([1,2,3,4,5])
print(arr[:3])

[1 2 3]


In [6]:
arr=np.array([1,2,3,4,5])
print(arr[1:])

[2 3 4 5]


In [7]:
arr=np.array([1,2,3,4,5])
print(arr[-3:-1])

[3 4]


In [8]:
arr=np.array([1,2,3,4,5])
print(arr[1:5:2])

[2 4]


In [9]:
arr=np.array([1,2,3,4,5])
print(arr[::2])

[1 3 5]


In [10]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:3])

[7 8]


In [11]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:3,2])

[3 8]


In [12]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [15]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[3,4,5,6,7]])
arr1=arr[1:,2:]
print(arr1)
arr1[0,2]=88
print(arr1)
print(arr)

[[ 8  9 10]
 [ 5  6  7]]
[[ 8  9 88]
 [ 5  6  7]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 88]
 [ 3  4  5  6  7]]


In [16]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[3,4,5,6,7]])
arr1=arr[2:,:]
print(arr1)
print(arr1.shape)

[[3 4 5 6 7]]
(1, 5)
