In [2]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value os arry1 is:")
print(array1)

The value os arry1 is:
[[1 2 3]
 [4 5 6]]


In [3]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1
print("The value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]


In [4]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1
print("The value of array2 is:")
print(array2)
array2[0][0]=11
print("The updated array2 is:")
print(array2)
print("The updated array2 is:")
print(array1)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated array2 is:
[[11  2  3]
 [ 4  5  6]]
The updated array2 is:
[[11  2  3]
 [ 4  5  6]]


In [5]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1
print("The value of array2 is:")
print(array2)
array1.shape=1,-1
print("The updated value of array1 is:")
print(array1)
print("The updated value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array1 is:
[[1 2 3 4 5 6]]
The updated value of array2 is:
[[1 2 3 4 5 6]]


In [6]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.view()
print("The value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]


In [7]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.view()
print("The value of array2 is:")
print(array2)
array2[0][0]=11
print("The updated array2 is:")
print(array2)
print("The updated array2 is:")
print(array1)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated array2 is:
[[11  2  3]
 [ 4  5  6]]
The updated array2 is:
[[11  2  3]
 [ 4  5  6]]


In [8]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.view()
print("The value of array2 is:")
print(array2)
array1.shape=1,-1
print("The updated value of array1 is:")
print(array1)
print("The updated value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array1 is:
[[1 2 3 4 5 6]]
The updated value of array2 is:
[[1 2 3]
 [4 5 6]]


In [9]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.copy()
print("The value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]


In [10]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.copy()
print("The value of array2 is:")
print(array2)
array2[0][0]=11
print("The updated array2 is:")
print(array2)
print("The updated array2 is:")
print(array1)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated array2 is:
[[11  2  3]
 [ 4  5  6]]
The updated array2 is:
[[1 2 3]
 [4 5 6]]


In [11]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.copy()
print("The value of array2 is:")
print(array2)
array1.shape=1,-1
print("The updated value of array1 is:")
print(array1)
print("The updated value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array1 is:
[[1 2 3 4 5 6]]
The updated value of array2 is:
[[1 2 3]
 [4 5 6]]
