In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])
print(arr[1])

1
2


In [2]:
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [3]:
arr=np.array([[1,2,3,4]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr[0,0])
print(arr[0,3])

[[1 2 3 4]]
2
(1, 4)
1
4


In [4]:
list1=[1,2,3,4,5]
arr=np.array(list1)
print(arr[[2,4]])

[3 5]


In [5]:
arr=np.array([[[1,2,3]]])
print(arr[0,0,2])

3


In [6]:
arr=np.array([[[1,2,3],[4,5,6]]])
print(arr[0,1,2])

6


In [7]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [8]:
arr=np.array([1,2,3,4,5])
print(arr[-1])

5


In [9]:
arr=np.array([[1,2,3,4,5]])
print(arr[0,-1])

5


In [10]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10


In [11]:
list1=[6,7,8,9,10]
arr=np.array([list1])
print(arr)
print(arr>7)

[[ 6  7  8  9 10]]
[[False False  True  True  True]]


In [12]:
list1=[6,7,8,9,10]
arr=np.array([list1])
print(arr)
print(arr>7)
print(arr[arr>7])

[[ 6  7  8  9 10]]
[[False False  True  True  True]]
[ 8  9 10]


In [13]:
nums=np.arange(20)
print(nums)
odd_num=nums[nums%2==1]
print(odd_num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
