In [1]:
list1=[1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [2]:
list2=[1,"Hello",3.14,True,5]
print(list2)

[1, 'Hello', 3.14, True, 5]


In [3]:
import numpy as np
a1=np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [4]:
import numpy as np
a2=np.arange(0,10,2)
print(a2)
print(a2.shape)

[0 2 4 6 8]
(5,)


In [5]:
a3=np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [6]:
a3=np.zeros((2,3))
print(a3)
print(a3.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [7]:
a3=np.full((2,3),8)
print(a3)
print(a3.shape)

[[8 8 8]
 [8 8 8]]
(2, 3)


In [8]:
a3=np.eye(4)
print(a3)
print(a3.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [9]:
a3=np.random.random((2,4))
print(a3)
print(a3.shape)

[[0.88205061 0.06837114 0.62408763 0.38880602]
 [0.05341553 0.23478318 0.22530574 0.16850016]]
(2, 4)


In [ ]:
r1