In [1]:
import numpy as np
a = np.matrix([[1,2],[4,5]])
b = np.matrix([[7,8],[2,3]])
print("The matrix a is:")
print(a)
print("The matrix b is:")
print(b)

The matrix a is:
[[1 2]
 [4 5]]
The matrix b is:
[[7 8]
 [2 3]]


In [3]:
a = np.matrix([[1,2],[4,5]])
b = np.matrix([[7,8],[2,3]])
c = np.asmatrix(a)
d = np.asmatrix(b)
print("The matrix c is:")
print(c)
print("The matrix d is:")
print(d)

The matrix c is:
[[1 2]
 [4 5]]
The matrix d is:
[[7 8]
 [2 3]]


In [4]:
a = np.array([[1,2],[4,5]])
b = np.array([[7,8],[2,3]])
print("The product of a and b:")
print(a*b)
a1 = np.matrix([[1,2],[4,5]])
b1 = np.matrix([[7,8],[2,3]])
print("The product of a1 and b1:")
print(a1*b1)

The product of a and b:
[[ 7 16]
 [ 8 15]]
The product of a1 and b1:
[[11 14]
 [38 47]]


In [5]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The value of array A is:")
print(a)
print("The cumulative sunm of the elements in the array is:")
print(a.cumsum())

The value of array A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The cumulative sunm of tthe elements in the array is:
[ 1  3  6 10 15 21 28 36 45]


In [6]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The value of array A is:")
print(a)
print("The cumulative sunm of the elements in the array is:")
print(a.cumsum(axis=0))

The value of array A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The cumulative sunm of the elements in the array is:
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [7]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The value of array A is:")
print(a)
print("The cumulative sunm of the elements in the array is:")
print(a.cumsum(axis=1))

The value of array A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The cumulative sunm of the elements in the array is:
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
