In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [2]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [3]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [4]:
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7)
print(x)

1


In [5]:
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7,side='right')
print(x)

2


In [6]:
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,9,side='left')
print(x)

3


In [7]:
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,[1,2,3])
print(x)

[0 0 0]


In [8]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [9]:
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr=[]
for element in arr:
    if element % 2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [11]:
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [12]:
arr=np.array([41,42,43,44])
filter_arr=arr%2==0
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]
