In [1]:
import numpy as np
list=[1,2,3,4,5]
arr=np.array(list)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]
arr=np.array([list1,list2,list3])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [3]:
tuple=(1,2,3,4,5)
arr=np.array(tuple)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
set={1,2,3,4,5}
arr=np.array(set)
print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


In [5]:
dic={"Name":"Nirmal","Surname":"Gaud"}
arr=np.array(dic)
print(arr)
print(type(arr))

{'Name': 'Nirmal', 'Surname': 'Gaud'}
<class 'numpy.ndarray'>


In [6]:
set1={1,2}
set2={3,4}
arr=np.array([set1,set2])
print(arr)

[{1, 2} {3, 4}]


In [7]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
arr3=np.array(12)
arr2=np.array([1,2,3,4,5,6])
arr1=np.array([[1,2,3],[4,5,6]])
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Dimension of a arr3 is: ",arr3.ndim)
print("Dimension of a arr2 is: ",arr2.ndim)
print("Dimension of a arr1 is: ",arr1.ndim)
print("Dimension of a arr is: ",arr.ndim)

Dimension of a arr3 is:  0
Dimension of a arr2 is:  1
Dimension of a arr1 is:  2
Dimension of a arr is:  3


In [10]:
arr1=np.array([[1,2,3],[4,5,6]],ndmin=5)
print(arr1)
print("Number of dimension: ",arr1.ndim)

[[[[[1 2 3]
    [4 5 6]]]]]
Number of dimension:  5
