In [2]:
import numpy as np
from numpy import random
x = random.randint(100)
print(x)

20


In [3]:
x = random.rand()
print(x)

0.30106937302505266


In [4]:
x=random.randint(100,size=(5))
print(x)

[60 51 82 44 46]


In [5]:
x=random.randint(100,size=(3,5))
print(x)

[[60 58 23 39 81]
 [79  4 62 43  4]
 [57 10 49 87 92]]


In [7]:
x = random.rand(5)
print(x)

[0.12531041 0.40076896 0.69383974 0.52875618 0.72126514]


In [8]:
x = random.rand(3,5)
print(x)

[[0.66493308 0.86214348 0.26313204 0.591477   0.74953658]
 [0.20509506 0.4552157  0.42424981 0.83529713 0.03654221]
 [0.62395896 0.63542337 0.33459779 0.86157089 0.24415915]]


In [9]:
x=random.choice([3,5,7,9])
print(x)

7


In [10]:
x=random.choice([3,5,7,9],size=(3,5))
print(x)

[[3 5 5 3 3]
 [5 7 7 9 9]
 [9 5 5 7 5]]
