In [2]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
array2=array1.copy()
array2[0][0]=11
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]]
[[11  2  3]
 [ 4  5  6]]


In [5]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
array2=array1.copy()
array1[0][0]=11
print(array1)
print(array2)

[[11  2  3]
 [ 4  5  6]]
[[1 2 3]
 [4 5 6]]


In [3]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
array2=array1.view()
array2[0][0]=11
print(array1)
print(array2)

[[11  2  3]
 [ 4  5  6]]
[[11  2  3]
 [ 4  5  6]]


In [4]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
array2=array1.view()
array1[0][0]=11
print(array1)
print(array2)

[[11  2  3]
 [ 4  5  6]]
[[11  2  3]
 [ 4  5  6]]


In [7]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
array2=array1.copy()
array3=array1.view()
print(array2.base)
print(array3.base)

None
[[1 2 3]
 [4 5 6]]


In [8]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print(array1.shape)

(2, 3)


In [9]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list,ndmin=5)
print(array1)
print("Shape of array",array1.shape)

[[[[[1 2 3]
    [4 5 6]]]]]
Shape of array (1, 1, 1, 2, 3)


In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)b

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(2,3,2).base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,-1,2)
print(newarr)

[[[[ 1  2]]

  [[ 3  4]]

  [[ 5  6]]]


 [[[ 7  8]]

  [[ 9 10]]

  [[11 12]]]]
