In [4]:
arr=np.array([[[1,2,3]]])
print(arr[0,0,2])

3


In [ ]:
import numpy as np

In [5]:
arr=np.array([[[1,2,3],[4,5,6]]])
print(arr)
print(arr[0,0,2])
print(arr[0,1,1])

[[[1 2 3]
  [4 5 6]]]
3
5


In [6]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [7]:
arr=np.array([1,2,3,4,5])
print(arr[-1])

5


In [12]:
arr=np.array([1,2,3,4,5])
print(arr[-2])

4


In [9]:
arr=np.array([[1,2,3,4,5]])
print(arr[0,-2])

4


In [10]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5


In [13]:
list=[6,7,8,9,10]
arr=np.array(list)
print(arr)
print(arr>7)

[ 6  7  8  9 10]
[False False  True  True  True]


In [14]:
list=[6,7,8,9,10]
arr=np.array(list)
print(arr)
print(arr>7)
print(arr[arr>7])

[ 6  7  8  9 10]
[False False  True  True  True]
[ 8  9 10]


In [17]:
nums=np.arange(20)
print(nums)
print(nums%2==1)
print(nums[nums%2==1])
odd_num=nums[nums%2==1]
print(odd_num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [18]:
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [19]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [21]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3]
[4 5 6]


In [24]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
for x in np.arange(2):
    for y in np.arange(x,3):
        print(arr[x,y])
    y=0

[[1 2 3]
 [4 5 6]]
(2, 3)
1
2
3
5
6


In [25]:
arr=np.array([1,2,3])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [27]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[1:, ::2]):
    print(x)

5
7


In [29]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[1:, ::]):
    print(x)

5
6
7
8


In [30]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[0:1, 2:4]):
    print(x)

3
4


In [28]:
arr=np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [31]:
arr=np.array([[1,2,3],[4,5,6]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [32]:
arr=np.array([[[1,2,3]]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3


In [33]:
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[1,2,3],[4,5,6]])
print("Addition of A and B is: ")
print(arr+arr1)

Addition of A and B is: 
[[ 2  4  6]
 [ 8 10 12]]


In [34]:
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[1,2,3],[4,5,6]])
print("Substraction of A and B is: ")
print(arr-arr1)

Substraction of A and B is: 
[[0 0 0]
 [0 0 0]]


In [35]:
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[1,2,3],[4,5,6]])
print("Multiplication of A and B is: ")
print(arr*arr1)

Multiplication of A and B is: 
[[ 1  4  9]
 [16 25 36]]


In [36]:
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[1,2,3],[4,5,6]])
print("Division of A and B is: ")
print(arr/arr1)

Division of A and B is: 
[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
names=np.array(['Nirmal','Priyanka','Reshma'])
heights=np.array([1.5,1.78,1.6])
weights=np.array([65,46,59])
bmi=weights/heights**2
print(bmi)
print("The body mass index (BMI) of Nirmal, Priyanka, and Reshma is: ",bmi)
print("Overweight: ",names[bmi>25])
print("Underweight: ",names[bmi<18.5])
print("Healthy: ",names[(bmi>=18.5)&(bmi<=25)])

[28.88888889 14.51836889 23.046875  ]
The body mass index (BMI) of Nirmal, Priyanka, and Reshma is:  [28.88888889 14.51836889 23.046875  ]
Overweight:  ['Nirmal']
Underweight:  ['Priyanka']
Healthy:  ['Reshma']


In [39]:
x=np.array([2,3])
y=np.array([4,2])
print(np.multiply(x,y))
print("The dot product of x and y is: ",np.dot(x,y))

[8 6]
The dot product of x and y is:  14


In [40]:
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[1,2,3],[4,5,6]])
print(np.multiply(arr,arr1))
print("The dot product of x and y is: ",np.dot(x,y))

[[ 1  4  9]
 [16 25 36]]
The dot product of x and y is:  14


In [42]:
arr=np.array([1,2,3,4,5,6,7,8,4, 5, 8,2])
x=np.where(arr==4)
print(x)

(array([3, 8], dtype=int64),)


In [43]:
arr=np.array([1,2,3,4,5,6,7,8,4, 5, 8,2])
x=np.where(arr%2==0)
print(x)

(array([ 1,  3,  5,  7,  8, 10, 11], dtype=int64),)


In [44]:
arr=np.array([1,2,3,4,5,6,7,8,4, 5, 8,2])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4, 6, 9], dtype=int64),)


In [47]:
arr=np.array([1,2,3,4,5,6,7,8,4, 5, 8,2])
x=np.searchsorted(arr,6)
print(x)

5


In [48]:
arr=np.array([1,2,3,4,5,6,7,8,4, 5, 8,2])
x=np.searchsorted(arr,8)
print(x)

12


In [49]:
arr=np.array([1,2,3,4,5,6,7,8,4, 5, 8,2])
x=np.searchsorted(arr,5)
print(x)

4


In [50]:
arr=np.array([5,6,7,8,9,1])
x=np.searchsorted(arr,6)
print(x)

1


In [51]:
arr=np.array([7,5,8,7,6,9,1])
x=np.searchsorted(arr,6)
print(x)

2


In [52]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [53]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8],[5,6,7,8,9]])
print("The NumPy Array is:")
print(arr)
arr1=arr[1:3, :3]
print("The Sliced Numpy array is:")
print(arr1)

The NumPy Array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [5 6 7 8 9]]
The Sliced Numpy array is:
[[4 5 6]
 [5 6 7]]


In [54]:
arr=np.array([1,2,3,4,5,6,7,8,4, 5, 8,2])
print(arr[1:5:3])

[2 5]
