## Numpy-Practise code 1

In [1]:
import numpy as np
my_array=np.array([10,12,14,16,20,25])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[10 12 14 16 20 25]
int32
4


In [2]:
my_array=np.array([10.5,12.67,14.98,16.02,20.54,25.92])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[10.5  12.67 14.98 16.02 20.54 25.92]
float64
8


In [3]:
my_array=np.array(["Red","Green","Orange"])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['Red' 'Green' 'Orange']
<U6
24


In [4]:
my_array=np.array(["Red","Green","Orange",12,67.34])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['Red' 'Green' 'Orange' '12' '67.34']
<U32
128


In [5]:
my_array=np.array(["1990-10-04","1989-05-06","1990-11-04"])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
<U10
40


In [6]:
my_array3=my_array.astype("M")
print(my_array3.dtype)
print(my_array3.dtype.itemsize)

datetime64[D]
8


In [7]:
x=(1,2,3,4,5)
y=np.array(x)
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
x={1,2,3,4,5}
y=np.array(x)
print(y)
print(type(y))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


In [9]:
x=[1,2,3,4,5]
y=np.array(x)
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
x=[1,2,3,4,5]
y=[1,2,3,4,5]
z=[1,2,3,4,5]
num_2d=np.array([x,y,z])
num_2d.shape

(3, 5)

In [11]:
x=[1,2,3,4,5]
y=[1,2,3,4,5]
z=[1,2,3,4,5]
num_3d=np.array([[x,y,z]])
num_3d.shape

(1, 3, 5)

In [12]:
x=[1,2,3,4,5]
y=[1,2,3,4,5]
z=[1,2,3,4,5]
num_4d=np.array([[[x,y,z]]])
num_4d.shape

(1, 1, 3, 5)

In [13]:
num_arr=np.arange(5,11)
print(num_arr)

[ 5  6  7  8  9 10]


In [14]:
num_arr=np.arange(5,11,3)
print(num_arr)

[5 8]


In [15]:
arr=np.array([1,2,3,4,5])
arr1=arr.copy()
arr[0]=42
print(arr)
print(arr1)

[42  2  3  4  5]
[1 2 3 4 5]


In [16]:
ones_array=np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [17]:
arr=np.array([1,2,3,4,5])
arr1=arr.view()
arr[0]=42
print(arr)
print(arr1)

[42  2  3  4  5]
[42  2  3  4  5]


In [18]:
arr=np.array([1,2,3,4,5])
arr1=arr.view()
arr1[0]=24
print(arr)
print(arr1)

[24  2  3  4  5]
[24  2  3  4  5]


In [19]:
arr=np.array([1,2,3,4,5])
arr1=arr.view()
arr2=arr1.view()
arr1[0]=42
print(arr)
print(arr1)
print(arr2)

[42  2  3  4  5]
[42  2  3  4  5]
[42  2  3  4  5]


In [20]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [21]:
arr=np.array([1,2,3,4,5], ndmin=5)
print(arr)
print('Shape of array: ',arr.shape)

[[[[[1 2 3 4 5]]]]]
Shape of array:  (1, 1, 1, 1, 5)


In [22]:
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]], ndmin=5)
print(arr)
print('Shape of array: ',arr.shape)

[[[[[1 2 3 4 5]
    [1 2 3 4 5]]]]]
Shape of array:  (1, 1, 1, 2, 5)


In [23]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [25]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2,-1)
print(newarr)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]]


In [29]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(-2,1,2,2)
print(newarr)

[[[[ 1  2]
   [ 3  4]]]


 [[[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]]]


In [30]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,-1,2)
print(newarr)

[[[[ 1  2]]

  [[ 3  4]]

  [[ 5  6]]]


 [[[ 7  8]]

  [[ 9 10]]

  [[11 12]]]]


In [31]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is: ")
print(array1)

The value of array1 is: 
[[1 2 3]
 [4 5 6]]


In [32]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1
print("The value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]


In [33]:
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is: ")
print(array1)
array2=array1
print("The value of array2 is: ")
print(array2)
array2[0][0]=11
print("The updated array2 is: ")
print(array2)
print("The updated array1 is: ")
print(array1)

The value of array1 is: 
[[1 2 3]
 [4 5 6]]
The value of array2 is: 
[[1 2 3]
 [4 5 6]]
The updated array2 is: 
[[11  2  3]
 [ 4  5  6]]
The updated array1 is: 
[[11  2  3]
 [ 4  5  6]]


In [34]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])

1
2


In [35]:
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [36]:
arr=np.array([[1,2,3,4,5]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr[0,0])
print(arr[0,3])

[[1 2 3 4 5]]
2
(1, 5)
1
4


In [38]:
list1=[1,2,3,45,5,6]
arr=np.array(list1)
print(arr)
print(arr[[1,3]])

[ 1  2  3 45  5  6]
[ 2 45]


In [39]:
arr=np.array([[[1,2,3],[4,5,6]]])
print(arr)
print(arr[0,0,2])
print(arr[0,1,2])

[[[1 2 3]
  [4 5 6]]]
3
6
