In [3]:
import numpy as np
arr=np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])
print("The Numpy Array is:")
print(arr)
arr1=arr[2:,:]
print("The sliced Numpy Array is:")
print(arr1)
print("The shape of Sliced Numpy Array is:")
print(arr1.shape)

The Numpy Array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The sliced Numpy Array is:
[[9 8 7 6 5]]
The shape of Sliced Numpy Array is:
(1, 5)


In [2]:
import numpy as np

In [4]:
a4=np.zeros((2,3))
print(a4)
print(a4.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [5]:
a4=np.zeros((2,))
print(a4)
print(a4.shape)

[0. 0.]
(2,)


In [7]:
a4=np.zeros(2)
print(a4)
print(a4.shape)

[0. 0.]
(2,)


In [8]:
a4=np.zeros((2,3))
print(a4)
print(a4.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [9]:
a4=np.full((2,3),8)
print(a4)
print(a4.shape)

[[8 8 8]
 [8 8 8]]
(2, 3)


In [12]:
a4=np.full((2),8)
print(a4)
print(a4.shape)

[8 8]
(2,)


In [13]:
a6=np.eye(4)
print(a6)
print(a6.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [15]:
a6=np.eye(10)
print(a6)
print(a6.shape)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
(10, 10)


In [16]:
a7=np.random.random((2,4))
print(a7)
print(a7.shape)

[[0.20428881 0.51510929 0.38880703 0.39730782]
 [0.64137959 0.51997506 0.94811682 0.39042989]]
(2, 4)


In [17]:
list1=[1,2,3,4,5]
print(list1)
r1=np.array(list1)
print(r1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [18]:
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [20]:
arr=np.array([1.1,2.1,0])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True False]
bool


In [22]:
arr = np.array([1,2,3])
for x in arr:
    print(arr)

[1 2 3]
[1 2 3]
[1 2 3]


In [23]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [24]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [25]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,10)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [26]:
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [27]:
num1=6
num2=18
x=np.lcm(num1,num2)
print(x)

18


In [28]:
#lcm can only consists of 2 variable
x=np.lcm(6,5)
print(x)

30


In [29]:
# reduce is used to apply binary operation on an array and iterate until it found single value
# 1st it will find the lcm of two number and than next number 9
arr=np.array([3,6,9])
x=np.lcm.reduce(arr)
print(x)

18


In [32]:
arr=np.array([1,11])
x=np.lcm.reduce(arr)
print(x)

11


In [33]:
num1=12
num2=24
x=np.gcd(num1,num2)
print(x)

12


In [34]:
arr=np.array([20,8,32,36,16])
x=np.gcd.reduce(arr)
print(x)

4


In [35]:
#You can create a two-Dimensional array of all ones by passing the number of
#rows and columns as the first and second parameter of theones() method, as
#shown below
ones_array=np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
# The zeros() method can be used to create a Numpy array of all zeros. Here
# is an example
zeros_array=np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [38]:
#You can create a two-dimentional array of all zeros by passing the number of
#rows and columns as the first and second parameter of the zeros() method,
#as shown below:
zeros_array=np.zeros((6,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
# The eye() method is used to create an identity matrix in the form of a 2 dimentional
# Numpy array. An identity matrix contains is along the diagonal,
# while the rest of the element are 0 in the array.
eyes_array=np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
# The random.rand() function from the Numpy module can be create
# a Numpy array with uniform distribution
uniform_random=np.random.rand(4,5)
print(uniform_random)

[[0.76780606 0.67886709 0.3577254  0.24602138 0.501932  ]
 [0.04806188 0.56949318 0.55443533 0.63871128 0.40278001]
 [0.85718572 0.17596929 0.78450878 0.80560144 0.66553314]
 [0.74480641 0.80988047 0.13573176 0.13513544 0.60334218]]


In [41]:
#Finally, the random.randint() function from the Numpy module can be used 
# to create a Numpy array with random intergers between a certain range.
integer_random=np.random.randint(10,50,5)
print(integer_random)

[37 43 35 23 22]


In [43]:
integer_random=np.random.randint(1,11,size=(4,5))
print(integer_random)

[[ 6  1  5  9  4]
 [ 1  2  3  3  3]
 [10  5  1  9  2]
 [ 3  2  7  1  7]]


In [44]:
integer_random=np.random.randint(1,11,size=(2,4,5))
print(integer_random)

[[[ 9 10  6  3  5]
  [10 10  1  9  3]
  [ 8  4  6  9  9]
  [ 5  8  5  8 10]]

 [[ 5  5  5  2  7]
  [ 8  9  4  5  6]
  [ 9  4  1  3 10]
  [ 8  7  6  5 10]]]


In [45]:
integer_random=np.random.randint(1,11,size=(3,2,4,5))
print(integer_random)

[[[[ 1  3  8  9  2]
   [ 8  8 10 10  4]
   [ 9  2  9  5  7]
   [ 1  4  6  5  1]]

  [[ 7  2  7  7  6]
   [ 1  2  5  4  9]
   [ 4  5  5  5  2]
   [ 5  9 10  4  9]]]


 [[[ 3  5  2  8  5]
   [ 4  9 10 10  3]
   [ 6  3  2  4  5]
   [ 8  7  8  5  9]]

  [[10  5 10  6  6]
   [ 1  8  5 10  3]
   [ 7  7  1  6  2]
   [ 9  3  2  8  1]]]


 [[[ 5  1  8  5  5]
   [ 4  7  6  4  5]
   [ 2  6  9  3  3]
   [ 8  5  8  1  3]]

  [[ 2  3  4  8  2]
   [ 8  4 10  7  4]
   [10  8  8  2  5]
   [ 9  1  7  8 10]]]]


In [46]:
my_array=np.array(["Red","Green","Orange"])
print(my_array)
extended=np.append(my_array,"Yellow")
print(extended)

['Red' 'Green' 'Orange']
['Red' 'Green' 'Orange' 'Yellow']


In [47]:
zeros_array=np.zeros((3,3))
print(zeros_array)
print("Extended Array")
extended=np.append(zeros_array,[[1,2,3]], axis=0)
print(extended)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended Array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 2. 3.]]


In [48]:
zeros_array=np.zeros((3,3))
print(zeros_array)
print("Extended Array")
extended=np.append(zeros_array,[[1],[2],[3]], axis=1)
print(extended)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended Array
[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]]


In [50]:
my_array=np.array(['Red',"Green","Orange"])
print(my_array)
print("After Deletion")
updated_array=np.delete(my_array,1)
print(updated_array)

['Red' 'Green' 'Orange']
After Deletion
['Red' 'Orange']


In [51]:
y_array=np.array(['Red',"Green","Orange"])
print(my_array)
print("After Deletion")
updated_array=np.delete(my_array,[1,2])
print(updated_array)

['Red' 'Green' 'Orange']
After Deletion
['Red']


In [55]:
y_array=np.array(["Red","Green","Orange","Yellow"])
print(my_array)
print("After Deletion")
updated_array=np.delete(y_array, [1,3])
print(updated_array)

['Red' 'Green' 'Orange']
After Deletion
['Red' 'Orange']


In [56]:
integer_random=np.random.randint(1,11, size=(4,5))
print(integer_random)
print("After Deletion")
updated_array=np.delete(integer_random, 1, axis=0)
print(updated_array)

[[ 4  8  8  3  7]
 [ 5 10  5  6  4]
 [ 6 10  3  7  4]
 [ 5  9  9  8  5]]
After Deletion
[[ 4  8  8  3  7]
 [ 6 10  3  7  4]
 [ 5  9  9  8  5]]


In [57]:
integer_random=np.random.randint(1,11, size=(4,5))
print(integer_random)
print("After Deletion")
updated_array=np.delete(integer_random, 0, axis=0)
print(updated_array)

[[ 7  4  8  9  7]
 [ 7  8  2 10  4]
 [ 7  8  6  1  7]
 [ 3  8  3  6 10]]
After Deletion
[[ 7  8  2 10  4]
 [ 7  8  6  1  7]
 [ 3  8  3  6 10]]


In [58]:
print("Unsorted array")
my_array=np.random.randint(1,20,10)
print(my_array)
print("\nsorted array")
sorted_array=np.sort(my_array)
print(sorted_array)

Unsorted array
[12 11 10  2 12 19 14  4  5 17]

sorted array
[ 2  4  5 10 11 12 12 14 17 19]


In [59]:
print("Unsorted array")
my_array=np.array(["Red","Green","Blue","Yellow"])
print(my_array)
print("\nsorted array")
sorted_array=np.sort(my_array)
print(sorted_array)

Unsorted array
['Red' 'Green' 'Blue' 'Yellow']

sorted array
['Blue' 'Green' 'Red' 'Yellow']


In [61]:
print("Unsorted array")
my_array=np.array(["True","False","true","false","True","False"])
print(my_array)
print("\nsorted array")
sorted_array=np.sort(my_array)
print(sorted_array)

Unsorted array
['True' 'False' 'true' 'false' 'True' 'False']

sorted array
['False' 'False' 'True' 'True' 'false' 'true']


In [62]:
print("Unsorted array")
my_array=np.random.randint(1,20,size=(4,6))
print(my_array)
print("\nsorted array")
sorted_array=np.sort(my_array)
print(sorted_array)

Unsorted array
[[11  8  4  7 11 14]
 [ 9  2  2 14 16  7]
 [12  1 18 13  7 18]
 [18 17 13 12  1  4]]

sorted array
[[ 4  7  8 11 11 14]
 [ 2  2  7  9 14 16]
 [ 1  7 12 13 18 18]
 [ 1  4 12 13 17 18]]


In [64]:
print("Unsorted array")
my_array=np.array([3,8,4,7,11,5,0,2,87,34,5,0,2])
print(my_array)
print("\nsorted array")
sorted_array=np.sort(my_array)
reverse_sorted=np.flipud(sorted_array)
print(reverse_sorted)
print(sorted_array)

Unsorted array
[ 3  8  4  7 11  5  0  2 87 34  5  0  2]

sorted array
[87 34 11  8  7  5  5  4  3  2  2  0  0]
[ 0  0  2  2  3  4  5  5  7  8 11 34 87]


In [70]:
print("1D array")
my_array=np.random.randint(1,20,10)
print(my_array)
print("\n2D array")
twodarray=my_array.reshape(2,5)
print(twodarray)
print("\n3D array")
threedarray=my_array.reshape(1,2,5)
print(threedarray)

1D array
[ 2 19  1  4 15 13  9  7 15  1]

2D array
[[ 2 19  1  4 15]
 [13  9  7 15  1]]

3D array
[[[ 2 19  1  4 15]
  [13  9  7 15  1]]]


In [74]:
arr=np.array([10,12,14,16,18,20])
np.save("E:\Internship\Python",arr)

In [75]:
arr=np.array([10,12,14,16,18,20])
np.save("E:\Internship\Python\my_array.txt",arr)

In [76]:
a=np.array(([i+j for i in range(5)
            for j in range(5)]))
print("a is:")
print(a)
np.save('file',a)
print("the array is saved in the file.npy")
b=np.load('file.npy')
print("b is:")
print("b is printed from file.npy")

a is:
[0 1 2 3 4 1 2 3 4 5 2 3 4 5 6 3 4 5 6 7 4 5 6 7 8]
the array is saved in the file.npy
b is:
b is printed from file.npy


In [77]:
my_array=np.array([2,3,4,8,6,10,12])
print(my_array)
print("mean:")
print(np.mean(my_array))

[ 2  3  4  8  6 10 12]
mean:
6.428571428571429


In [78]:
my_array=np.array([2,3,4,8,6,10,12])
print(my_array)
print("median:")
print(np.median(my_array))

[ 2  3  4  8  6 10 12]
median:
6.0


In [79]:
my_array=np.random.randint(1,20,size=(2,3))
print(my_array)
print("mean:")
print(np.mean(my_array, axis=1))
print(np.mean(my_array, axis=0))

[[13 14  8]
 [15 19 19]]
mean:
[11.66666667 17.66666667]
[14.  16.5 13.5]


In [80]:
my_array=np.random.randint(1,20,size=(2,3))
print(my_array)
print("median:")
print(np.median(my_array, axis=1))#rows
print(np.median(my_array, axis=0))#columns

[[ 5  7  2]
 [ 8  5 12]]
median:
[5. 8.]
[6.5 6.  7. ]


In [86]:
my_array=np.array([2,3,4,8,6,10,12])
print(my_array)
print("min:")
print(np.amin(my_array))

[ 2  3  4  8  6 10 12]
min:
2


In [87]:
my_array=np.array([2,3,4,8,6,10,12])
print(my_array)
print("max:")
print(np.amax(my_array))

[ 2  3  4  8  6 10 12]
max:
12


In [88]:
my_array=np.random.randint(1,20,size=(2,3))
print(my_array)
print("min:")
print(np.amin(my_array, axis=1))#rows
print(np.amin(my_array, axis=0))#columns

[[ 5 12 14]
 [15  7 17]]
min:
[5 7]
[ 5  7 14]


In [89]:
my_array=np.random.randint(1,20,size=(2,3))
print(my_array)
print("max:")
print(np.amax(my_array, axis=1))#rows
print(np.amax(my_array, axis=0))#columns

[[ 4  2  7]
 [ 1  5 17]]
max:
[ 7 17]
[ 4  5 17]


In [90]:
my_array=np.array([2,3,4,8,6,10,12])
print(my_array)
print("std value:")
print(np.std(my_array))

[ 2  3  4  8  6 10 12]
std value:
3.45820526768863


In [91]:
my_array=np.random.randint(1,20,size=(2,3))
print(my_array)
print("std:")
print(np.std(my_array, axis=1))#rows
print(np.std(my_array, axis=0))#columns

[[15  3 18]
 [12  3 13]]
std:
[6.4807407  4.49691252]
[1.5 0.  2.5]


In [92]:
a1=np.array([2,3,4,8,6,10,12])
a2=np.array([6,10,12,0,-1,0.9])
print(a1)
print(a2)
print("correlation value:")
print(np.correlate(a1,a2))

[ 2  3  4  8  6 10 12]
[ 6.  10.  12.   0.  -1.   0.9]
correlation value:
[ 93.  154.8]


In [93]:
my_array=np.array([2,3,4,8,6,10,12,67,44,3,0,1,5,3,7,7])
print(my_array)
print("Unique value:")
print(np.unique(my_array))

[ 2  3  4  8  6 10 12 67 44  3  0  1  5  3  7  7]
Unique value:
[ 0  1  2  3  4  5  6  7  8 10 12 44 67]
